name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install clang
        sudo apt-get install libclang1
        sudo apt-get install libproj-dev
        sudo apt-get install libtiff-dev
        sudo apt-get install sqlite3
        rustup update stable
        cargo clean
    - name: Build and test with cargo
      run: |
        cargo test --all-features